services:
  alpha-engine:
    build: .
    container_name: alpha-engine
    environment:
      APP_ENV: local
      LOG_LEVEL: INFO
      SYMBOL: BTCUSDT
      MIN_SPREAD_PERCENT: "0.20"
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped
